name: jaxlib / osx-arm64

on:
  release:
    types:
      - published
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    name: jaxlib ${{ matrix.jaxlib-version }} / Python ${{ matrix.python-version }}
    runs-on: macos-10.15
    strategy:
      matrix:
        jaxlib-version: ['v0.1.73']
        python-version: ['3.8', '3.9']
        build-number: ['0']

    steps:
      - uses: actions/checkout@v2

      - name: Fetch JAX source
        run: |
          mkdir build
          cd build
          wget -q https://github.com/google/jax/archive/refs/tags/jaxlib-${{ matrix.jaxlib-version }}.tar.gz
          tar xf jaxlib-${{ matrix.jaxlib-version }}.tar.gz --strip-components=1 -C .
          git apply ../jaxlib-v0.1.73.patch
          
      - name: Cache Bazel build products
        uses: actions/cache@v2
        with:
          path: '~/bazel-build-cache'
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.build-number }}-${{ matrix.jaxlib-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.build-number }}-${{ matrix.jaxlib-version }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install build dependencies
        run: |
          python -m pip install -U pip
          python -m pip install numpy scipy wheel future six

      - name: Build jaxlib
        run: |
          cd build
          python build/build.py --target_cpu darwin_arm64 --bazel_startup_options="--output_base=~/bazel-build-cache"

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./build/dist/*.whl

  index:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: git clone --single-branch --branch index https://github.com/dfm/custom-wheels index
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheels
      - run: |
          cd index
          rm -rf .git

          rsync -r ../wheels/ jaxlib
          python ../generate_index.py
          ls

          git init .
          git checkout -b index
          git add .
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating index"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/dfm/custom-wheels index
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
